### ISSUE TITLE
ISsue for KEN

### ISSUE THREAD

**Issue by usamaazhar** [usamaazhar/LanguageTool.WordAddin#20]
reponing the issue

**Comment by kenwith** [comment]
@usamaazhar add label 'hello'

**Comment by kenwith** [comment]
@usamaazhar assign this issue to @kenwith

**Comment by kenwith** [comment]
@usamaazhar assign this item to @kenwith

**Comment by kenwith** [comment]
@usamaazhar assign this item to @TqrHsn

**Comment by kenwith** [comment]
@usamaazhar close this issue

**Comment by usamaazhar** [comment]
@usamaazhar open this issue

**Comment by usamaazhar** [comment]
@usamaazhar close this issue

**Comment by usamaazhar** [comment]
@usamaazhar close this issue
