### ISSUE TITLE
UsamaIssueCreatedByBot

### ISSUE THREAD

**Issue by usamaazhar** [usamaazhar/LanguageTool.WordAddin#21]
closing the issue

**Comment by usamaazhar** [comment]
@usamaazhar open issue with title test issue

**Comment by usamaazhar** [comment]
@usamaazhar open issue with title my issue

**Comment by usamaazhar** [comment]
@usamaazhar assign this item to @TqrHsn

**Comment by usamaazhar** [comment]
@usamaazhar unassign this issue from @TqrHsn

**Comment by usamaazhar** [comment]
@usamaazhar unassign this item from @TqrHsn

**Comment by usamaazhar** [comment]
@usamaazhar add label BOT

**Comment by usamaazhar** [comment]
@usamaazhar delete label BOT

**Comment by usamaazhar** [comment]
@usamaazhar open an issue with title my issue

**Comment by kenwith** [comment]
@usamaazhar close this issue

**Comment by kenwith** [comment]
@usamaazhar open this issue

**Comment by kenwith** [comment]
@usamaazhar add label 'cool one'

**Comment by kenwith** [comment]
@usamaazhar add label 'cool2'
